// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file FooTypeTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#include "FooTypeTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>
#include "FooType.hpp"


using namespace eprosima::fastdds::dds::xtypes;

// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_FooType_type_identifier(
        TypeIdentifierPair& type_ids_FooType)
{

    ReturnCode_t return_code_FooType {eprosima::fastdds::dds::RETCODE_OK};
    return_code_FooType =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "FooType", type_ids_FooType);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_FooType)
    {
        StructTypeFlag struct_flags_FooType = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_FooType = "FooType";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_FooType;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_FooType;
        CompleteTypeDetail detail_FooType = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_FooType, ann_custom_FooType, type_name_FooType.to_string());
        CompleteStructHeader header_FooType;
        header_FooType = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_FooType);
        CompleteStructMemberSeq member_seq_FooType;
        {
            TypeIdentifierPair type_ids_num;
            ReturnCode_t return_code_num {eprosima::fastdds::dds::RETCODE_OK};
            return_code_num =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int32_t", type_ids_num);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_num)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "num Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_num = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_num = 0x00000000;
            bool common_num_ec {false};
            CommonStructMember common_num {TypeObjectUtils::build_common_struct_member(member_id_num, member_flags_num, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_num, common_num_ec))};
            if (!common_num_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure num member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_num = "num";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_num;
            ann_custom_FooType.reset();
            CompleteMemberDetail detail_num = TypeObjectUtils::build_complete_member_detail(name_num, member_ann_builtin_num, ann_custom_FooType);
            CompleteStructMember member_num = TypeObjectUtils::build_complete_struct_member(common_num, detail_num);
            TypeObjectUtils::add_complete_struct_member(member_seq_FooType, member_num);
        }
        {
            TypeIdentifierPair type_ids_msg;
            ReturnCode_t return_code_msg {eprosima::fastdds::dds::RETCODE_OK};
            return_code_msg =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_msg);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_msg)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_msg))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_msg = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_msg = 0x00000001;
            bool common_msg_ec {false};
            CommonStructMember common_msg {TypeObjectUtils::build_common_struct_member(member_id_msg, member_flags_msg, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_msg, common_msg_ec))};
            if (!common_msg_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure msg member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_msg = "msg";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_msg;
            ann_custom_FooType.reset();
            CompleteMemberDetail detail_msg = TypeObjectUtils::build_complete_member_detail(name_msg, member_ann_builtin_msg, ann_custom_FooType);
            CompleteStructMember member_msg = TypeObjectUtils::build_complete_struct_member(common_msg, detail_msg);
            TypeObjectUtils::add_complete_struct_member(member_seq_FooType, member_msg);
        }
        CompleteStructType struct_type_FooType = TypeObjectUtils::build_complete_struct_type(struct_flags_FooType, header_FooType, member_seq_FooType);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_FooType, type_name_FooType.to_string(), type_ids_FooType))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "FooType already registered in TypeObjectRegistry for a different type.");
        }
    }
}
