// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file FooType.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#ifndef FAST_DDS_GENERATED__FOOTYPE_HPP
#define FAST_DDS_GENERATED__FOOTYPE_HPP

#include <cstdint>
#include <string>
#include <utility>
#include <fastcdr/cdr/fixed_size_string.hpp>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(FOOTYPE_SOURCE)
#define FOOTYPE_DllAPI __declspec( dllexport )
#else
#define FOOTYPE_DllAPI __declspec( dllimport )
#endif // FOOTYPE_SOURCE
#else
#define FOOTYPE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define FOOTYPE_DllAPI
#endif // _WIN32

/*!
 * @brief This class represents the structure FooType defined by the user in the IDL file.
 * @ingroup FooType
 */
class FooType
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport FooType()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~FooType()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object FooType that will be copied.
     */
    eProsima_user_DllExport FooType(
            const FooType& x)
    {
                    m_num = x.m_num;

                    m_msg = x.m_msg;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object FooType that will be copied.
     */
    eProsima_user_DllExport FooType(
            FooType&& x) noexcept
    {
        m_num = x.m_num;
        m_msg = std::move(x.m_msg);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object FooType that will be copied.
     */
    eProsima_user_DllExport FooType& operator =(
            const FooType& x)
    {

                    m_num = x.m_num;

                    m_msg = x.m_msg;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object FooType that will be copied.
     */
    eProsima_user_DllExport FooType& operator =(
            FooType&& x) noexcept
    {

        m_num = x.m_num;
        m_msg = std::move(x.m_msg);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x FooType object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const FooType& x) const
    {
        return (m_num == x.m_num &&
           m_msg == x.m_msg);
    }

    /*!
     * @brief Comparison operator.
     * @param x FooType object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const FooType& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member num
     * @param _num New value for member num
     */
    eProsima_user_DllExport void num(
            int32_t _num)
    {
        m_num = _num;
    }

    /*!
     * @brief This function returns the value of member num
     * @return Value of member num
     */
    eProsima_user_DllExport int32_t num() const
    {
        return m_num;
    }

    /*!
     * @brief This function returns a reference to member num
     * @return Reference to member num
     */
    eProsima_user_DllExport int32_t& num()
    {
        return m_num;
    }


    /*!
     * @brief This function copies the value in member msg
     * @param _msg New value to be copied in member msg
     */
    eProsima_user_DllExport void msg(
            const std::string& _msg)
    {
        m_msg = _msg;
    }

    /*!
     * @brief This function moves the value in member msg
     * @param _msg New value to be moved in member msg
     */
    eProsima_user_DllExport void msg(
            std::string&& _msg)
    {
        m_msg = std::move(_msg);
    }

    /*!
     * @brief This function returns a constant reference to member msg
     * @return Constant reference to member msg
     */
    eProsima_user_DllExport const std::string& msg() const
    {
        return m_msg;
    }

    /*!
     * @brief This function returns a reference to member msg
     * @return Reference to member msg
     */
    eProsima_user_DllExport std::string& msg()
    {
        return m_msg;
    }



private:

    int32_t m_num{0};
    std::string m_msg;

};

#endif // _FAST_DDS_GENERATED_FOOTYPE_HPP_


