name: ubuntu

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: src/Fast-DDS-statistics-backend

      - name: Install apt packages
        run: |
          sudo apt -y install \
            doxygen \
            graphviz \
            imagemagick \
            python3 \
            python3-pip \
            python3-sphinxcontrib.spelling \
            python3-venv \
            software-properties-common \
            wget \
            libasio-dev \
            libtinyxml2-dev

      - name: Install python dependencies
        run: |
          sudo pip3 install -U \
            sphinx==3.0.3 \
            breathe==4.19.0 \
            doc8==0.8.0 \
            sphinx_rtd_theme==0.4.3 \
            sphinxcontrib.spelling==5.0.0 \
            sphinxcontrib-imagehelper==1.1.1 \
            colcon-common-extensions==0.2.1 \
            colcon-mixin==0.1.8 \
            vcstool==0.2.7 \
            GitPython==3.1.1 \
            setuptools==46.1.3

      - name: Fetch Fast DDS dependencies
        run: |
          wget https://raw.githubusercontent.com/eProsima/Fast-DDS/master/fastrtps.repos
          vcs import src < fastrtps.repos

      - name: Build workspace
        run: |
          cat src/Fast-DDS-statistics-backend/.github/workflows/colcon.meta
          colcon build --event-handlers=console_direct+ --metas src/Fast-DDS-statistics-backend/.github/workflows/colcon.meta

      - name: Run tests
        run: source install/setup.bash && colcon test --packages-select fastdds-statistics-backend --event-handlers=console_direct+

      - name: Upload Logs
        uses: actions/upload-artifact@v1
        with:
          name: colcon-logs-ubuntu
          path: log/
        if: always()
