# Nightly test workflow for Fast DDS Statistics Backend
name: nightly-ubuntu-ci

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  reusable_tests:
    strategy:
      fail-fast: false
      matrix:
        version:
        - fastdds_ref: 'v2'
          backend_ref: '1.x'
        - fastdds_ref: 'v3'
          backend_ref: 'main'
    name: reusable_tests
    uses: ./.github/workflows/reusable-ubuntu-ci.yml
    with:
      custom_version_build: ${{ matrix.version.fastdds_ref }}
      dependencies_artifact_postfix: '_nightly'
      ref: ${{ matrix.version.backend_ref }}
    secrets: inherit

