name: ubuntu

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: src/Fast-DDS-statistics-backend

      - uses: ./src/Fast-DDS-statistics-backend/.github/actions/install-apt-packages
      - uses: ./src/Fast-DDS-statistics-backend/.github/actions/install-python-packages
      - uses: ./src/Fast-DDS-statistics-backend/.github/actions/fetch-fastdds-repos

      - name: Build workspace
        run: |
          cat src/Fast-DDS-statistics-backend/.github/workflows/colcon.meta
          colcon build --event-handlers=console_direct+ --metas src/Fast-DDS-statistics-backend/.github/workflows/colcon.meta

      - name: Run tests
        run: source install/setup.bash && colcon test --packages-select fastdds-statistics-backend --event-handlers=console_direct+

      - name: Upload Logs
        uses: actions/upload-artifact@v1
        with:
          name: colcon-logs-ubuntu
          path: log/
        if: always()
